specVersion: 0.0.1
description: ''
repository: ''
schema: ./schema.graphql
network:
  endpoint: wss://archive.snakenet.hydradx.io
  dictionary: https://api.subquery.network/sq/StreetYo/hydradx-dictionary

  types: {
    "AssetPair": {
      "asset_in": "AssetId",
      "asset_out": "AssetId"
    },
    "Amount": "i128",
    "AmountOf": "Amount",
    "Address": "AccountId",
    "OrmlAccountData": {
      "free": "Balance",
      "frozen": "Balance",
      "reserved": "Balance"
    },
    "BalanceInfo": {
      "amount": "Balance",
      "assetId": "AssetId"
    },
    "Chain": {
      "genesisHash": "Vec<u8>",
      "lastBlockHash": "Vec<u8>"
    },
    "CurrencyId": "AssetId",
    "CurrencyIdOf": "AssetId",
    "Intention": {
      "who": "AccountId",
      "asset_sell": "AssetId",
      "asset_buy": "AssetId",
      "amount": "Balance",
      "discount": "bool",
      "sell_or_buy": "IntentionType"
    },
    "IntentionId": "Hash",
    "IntentionType": {
      "_enum": [
          "SELL",
          "BUY"
      ]
    },
    "LookupSource": "AccountId",
    "OrderedSet": "Vec<AssetId>",
    "Price": "Balance",
    "Fee": {
      "numerator": "u32",
      "denominator": "u32"
    }
  }

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBond
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Bonded
        - handler: handleReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward
        - handler: handleRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slash
        - handler: handleSlashed
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slashed
        - handler: handleStakingReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward
        - handler: handleStakingRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleStakingSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slash
        - handler: handleStakingSlashed
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slashed
